apiVersion: install.firefly.io/v1alpha1
kind: Clusterpedia
metadata:
  name: clusterpedia
  namespace: firefly-system
spec:
  controlplaneProvider:
    karmada:
      name: karmada 
    syncResources:
    - group: ""
      resources:
      - "pods"
      - "services"
    - group: "apps"
      resources:
      - "*"