apiVersion: toolkit.firefly.io/v1alpha1
kind: Foo
metadata:
  name: demo
  namespace: default
spec:
  manifests:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: micro-dao-2048
      namespace: default
    spec:
      replicas: 2
      selector:
        matchLabels:
          dce.daocloud.io/component: micro-dao-2048
      strategy:
        rollingUpdate:
          maxSurge: 25%
          maxUnavailable: 25%
        type: RollingUpdate
      template:
        metadata:
          creationTimestamp: null
          labels:
            c: b
            dce.daocloud.io/app: micro-dao-2048
            dce.daocloud.io/component: micro-dao-2048
        spec:
          containers:
          - env:
            - name: demo
              value: demo
            - name: demo1
              value: demo1
            image: daocloud.io/daocloud/dao-2048:latest
            imagePullPolicy: Always
            name: micro-dao-2048
            resources:
              limits:
                cpu: 128m
                memory: "67108864"
              requests:
                cpu: "0"
                memory: "0"
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30